title: Tahanima Chowdhury
description: Software Engineer, QA @ Therap (BD) Ltd.
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "safi.096z@gmail.com"
linkedin: "https://www.linkedin.com/in/safi-islam-612335208/"
github: "https://github.com/safislam1996"
# website: "http://tahanima.github.io/"
# medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
